[package]
name = "hardened_std"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
libc = { version = "0.2", default-features = false }

[lib]
name = "hardened_std"
path = "src/lib.rs"
